Add simulate
emqx/MQTTX pull request #1280
Opened 2023-05-06 04:22 UTC by wivwiv

### PR Checklist

#### What is the new behavior?

Users can use the new `simulate` command to simulate publishing messages in specific scenarios, such as the status reported by hundreds of telsa model 3 per second.

It helps users to generate a large number of the most realistic dynamic messages in a short time.

Although it sounds like a subset of bench, it should be a completely new feature.  

In the future it will be built with rich scenarios for IIoT, IoV, Energy and Power, etc. It also allows users to customize the simulator —— specify a `js` file to perform data generation, or even replay historical data from a database or stream.

**Usage**

```
$ mqttx sim -sc tesla -c 10
[2023/5/6] [12:19:08] › ℹ  Start simulation publishing, scenario: tesla, connections: 10, req interval: 10ms, message interval: 1000m

$ mqttx sim -f  ../scripts/scenarios/tesla.js -c 10
2023/5/6] [12:21:53] › ℹ  Start simulation publishing, scenario: ../scripts/scenarios/tesla.js, connections: 10, req interval: 10ms, message interval: 1000ms
```

```
$ mqttx sub -t +/# -v
[2023-5-6] [12:20:00] › topic: mqttx/simulate/tesla/mqttx_0038ee3e
payload: {"car_id":"XSDW6ET1XLDJ17357","display_name":"Chloe's Tesla","model":"S","trim_badging":"excepturi","exterior_color":"lavender","wheel_type":"beatae","spoiler_type":"autem","geofence":"Port Cletaburgh","state":"online","since":"2023-05-05T14:51:44.814Z","healthy":false,"version":"6.6.1", ...}
```

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Specific Instructions

Are there any specific instructions or things that should be known prior to review?

#### Other information

2023-05-08 07:15 UTC, Red-Asuka requested changes

2023-05-08 07:15 UTC, Red-Asuka commented on cli/src/types/global.d.ts
> +    verbose: boolean
These items are already defined in `BenchPublishOptions`.

```
count: number
interval: number
messageInterval: number
verbose: boolean
```

2023-05-08 07:15 UTC, Red-Asuka commented on cli/README.md
> +One of the `--scenario` and `--file` parameters must be specified, and if both are specified, the `--file` parameter is preferred.
I see that the simulator requires a generator method to return data and defaults to passing some parameters. An appropriate explanation should be provided here, along with a link to the simplest example of a simulator.

2023-05-08 07:15 UTC, Red-Asuka commented on cli/src/lib/pub.ts
> +              client.publish(topic || topicName, message, pubOpts.opts, (err) => {
The processing method for "publish" has not changed, only the input parameters are different. Please optimize the code.

2023-05-08 07:15 UTC, Red-Asuka commented on cli/src/utils/simulate.ts
> +interface ISimulator {
Move to `global.d.ts`.

2023-05-08 07:15 UTC, Red-Asuka commented on cli/tsconfig.json
> +  "include": ["src", "scenarios/*.js"]
Directly write `scenarios` to `/cli/src/scenarios/`, and use TypeScript.

2023-05-08 07:15 UTC, Red-Asuka commented on cli/tsconfig.json
> +    "allowJs": true,
Delete it.

2023-05-08 07:15 UTC, Red-Asuka commented on scripts/scenarios/tesla.js
> +const faker = require('faker')
Directly write `scenarios` to `/cli/src/scenarios/`, and use TypeScript.

2023-05-08 07:17 UTC, Red-Asuka commented
Please use Prettier to format the code.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/38158783/236759758-6d1b50a0-a6d3-4338-9aee-fd323cc42a72.png">

2023-05-08 07:19 UTC, Red-Asuka commented
Please provide users with the simplest example of a simulator and explain it in the documentation.

2023-05-08 07:52 UTC, Red-Asuka commented on cli/README.md
> +| -t, --topic <TOPIC... > | the message topic, optional, support %u (username), %c (client id), %i (index),  %sc (scenario) variables, defaults to `mqttx/simulate/%sc/%c` |
When using a custom scenario, the default topic %sc is undefined. Can the scenario file name be used instead?

<img width="760" alt="image" src="https://user-images.githubusercontent.com/38158783/236766083-d6a6217b-c99e-487e-afb2-ecb26c7f2662.png">

2023-05-08 08:21 UTC, ysfscream commented on cli/README.md
> +| simulate \| sim | Simulate publishing scenario-specific MQTT messages |
@wivwiv I think no matter `sim` or `simulate`, I think it's better to keep one, and I prefer `sim`, similar to `pub` `sub`.

2023-05-08 08:31 UTC, wivwiv commented on cli/tsconfig.json
> +    "allowJs": true,
I need to first put `scripts/scenarios/*.js` file to the `cli/src/scenarios` directory to ensure that the script is reusable inside the MQTTX App.

2023-05-08 08:32 UTC, ysfscream commented on cli/src/types/global.d.ts
> +  type CommandType = 'conn' | 'pub' | 'sub' | 'benchConn' | 'benchPub' | 'benchSub' | 'simulate' | 'sim'
Same here. keep one and I think.

2023-05-08 08:34 UTC, wivwiv commented on cli/tsconfig.json
> +  "include": ["src", "scenarios/*.js"]
For potential users, custom scripts can only use javascript.

- typescript is not widely used
- The `.ts` file may not be executed at runtime in --file mode?

2023-05-08 08:36 UTC, ysfscream commented on scripts/scenarios/tesla.js
> +}
Are these unified export fields and data?

2023-05-08 08:39 UTC, Red-Asuka commented on cli/tsconfig.json
> +  "include": ["src", "scenarios/*.js"]
My point is that the built-in scenarios should be written in TypeScript as much as possible, while user-defined ones can only use JavaScript.

2023-05-08 08:39 UTC, ysfscream reviewed
I'm more concerned about what to do if it's a custom local scenario data file. What is the complete process of using custom local scenario data files if not using the built-in simulated datasets?

2023-05-08 08:43 UTC, wivwiv commented on scripts/scenarios/tesla.js
> +}
Yes, in the future it might be possible to add an option to print the simulation data before starting.

This is inspired by the common plugin mechanism, which should always contain meta data for easy exchanges between different users.
A custom script can be treated as a plugin

2023-05-09 04:28 UTC, wivwiv commented on cli/README.md
> +| -t, --topic <TOPIC... > | the message topic, optional, support %u (username), %c (client id), %i (index),  %sc (scenario) variables, defaults to `mqttx/simulate/%sc/%c` |
fixed

2023-05-10 06:58 UTC, ysfscream approved these changes
LGTM

2023-05-10 07:34 UTC, Red-Asuka approved these changes

2023-05-10 07:36 UTC, merged