feat(desktop): add save button for new & edit connection
emqx/MQTTX pull request #1610
Opened 2024-03-23 16:45 UTC by XL-YiBai

### PR Checklist

If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md)

#### What is the current behavior?

When you want to make a new connection and fill in some (but not necessarly all) fields you can't temporailty save it and complement it later on. You can only choose Connect which is not always what you want. The same goes for editing connections.

#### Issue Number

#735

#### What is the new behavior?

When creating or editing connection information, the current information can be saved. Instead of clicking the `Connect` button to establish a connection.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Specific Instructions

Are there any specific instructions or things that should be known prior to review?

#### Other information

2024-03-25 02:10 UTC, Red-Asuka commented
@XL-YiBai Can you provide a screenshot after the modification?

2024-03-25 02:12 UTC, Red-Asuka approved these changes

2024-03-25 02:13 UTC, Red-Asuka commented
Looking good, can we also add this feature to the MQTTX Web?

2024-03-25 02:27 UTC, XL-YiBai commented
> @XL-YiBai Can you provide a screenshot after the modification?

I just uploaded a demonstration video. 😆
Create a new connection also has the same effect

2024-03-25 02:30 UTC, XL-YiBai commented
> Looking good, can we also add this feature to the MQTTX Web?

Of course, I will complete it in my free time.

2024-03-25 07:14 UTC, ysfscream commented
@XL-YiBai 

Thank you for your contribution; it indeed looks like a valuable enhancement. However, for MQTTX, modifying parameters and saving without immediate connection isn't a frequent operation. Thus, we propose integrating this functionality via a dropdown menu to maintain a cleaner interface. Specifically, we can have the "Connect" button for standard operations on the left, and a dropdown menu on the right with an option for "Save Only". This approach benefits us by:

1. **Keeping the UI Clean**: Reducing button clutter for a more focused user experience.
2. **Intuitive Functionality**: The dropdown menu clearly indicates additional actions without overwhelming the main interface.
3. **Streamlining Common Processes**: Ensures a smooth flow for the most common action—connecting—while offering flexibility for different user needs.

### Resources:

https://element-plus.org/zh-CN/component/dropdown.html

<img width="193" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/b81321b7-aa4f-48f7-9569-f9445b76736e">

the Right icon: 

<img width="181" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/91ad193f-ee41-4ee1-8f39-ca6920428add">

the UI design:

<img width="527" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/db7bc21b-3a20-4a08-9e71-960b6914695f">

2024-03-25 13:18 UTC, XL-YiBai commented
@ysfscream Thank you for your valuable suggestion and detailed design proposal. I will incorporate the suggested changes into the code.

2024-03-26 01:17 UTC, XL-YiBai commented
<img width="950" alt="image" src="https://github.com/emqx/MQTTX/assets/119273236/f85032ee-8ad7-4142-8ed6-4bc9aff18a3b">

2024-03-26 05:29 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +        const data = { ...this.record }
If this is merely for data validation without involving the original data processing, there's no need to perform object destructuring, which would add unnecessary performance overhead.

2024-03-26 05:33 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +      localStorage.setItem('newConnectionRecord', JSON.stringify(data))
I didn't quite understand this operation. Why store it in localStorage? Shouldn't it be about creating a new connection to the database?

2024-03-26 05:35 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +      localStorage.removeItem('newConnectionRecord')
This seems like an unnecessary step. Are you planning to delete the locally saved new connection and create it during the connect process?

2024-03-26 06:13 UTC, XL-YiBai commented on src/views/connections/ConnectionForm.vue
> +      localStorage.setItem('newConnectionRecord', JSON.stringify(data))
My understanding of the requirement raised by this [issue](https://github.com/emqx/MQTTX/issues/735) is that the configuration can be temporarily saved when creating a new connection, and the saved configuration can be displayed when clicking on the new connection again. 
Creating a new connection to the database can also achieve temporary storage, but in this way, the default configuration will always be displayed every time you click on the new connection. 
So I stored it in localStorage and then removed it when the user clicked `Connect` button.

2024-03-26 06:14 UTC, XL-YiBai commented on src/views/connections/ConnectionForm.vue
> +      localStorage.setItem('newConnectionRecord', JSON.stringify(data))
Sorry. It seems that I misunderstood, I will modify the code.

2024-03-26 06:25 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +      localStorage.setItem('newConnectionRecord', JSON.stringify(data))
Okay, I understand what you mean now. Actually, it doesn't need to be so complicated. Let's simplify the requirements. We just need to create or update a connection's information. We can fully reuse the previous code for saving the connection and navigating to the connection. In the "save" action, all we need to do is not to navigate to the connection page and perform the automatic connection operation. Do you understand what I mean? 

```js
// update ActiveConnection & connect
if (res && res.id) {
  this.changeActiveConnection({
    id: res.id,
    client: {
      connected: false,
    },
  });
  this.$emit('connect');
  this.$router.push(`/recent_connections/${res.id}`);
} else {
  this.$message.error(msgError);
  this.$log.error(msgError);
}
```

We just don't need to emit a 'connect': `  this.$emit('connect');`; in my understanding, everything else is the same.

2024-03-26 06:32 UTC, ysfscream commented on web/src/utils/api/connection.ts
> +}
From the desktop requirements just mentioned, it's the same for the Web. Just create a new connection without automatically connecting it.

Therefore, these unnecessary storage operations can be removed.

2024-03-26 06:37 UTC, XL-YiBai commented on src/views/connections/ConnectionForm.vue
> +      localStorage.setItem('newConnectionRecord', JSON.stringify(data))
Yes, I understand. I have made the problem more complicated. 👀

2024-03-26 09:32 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +  }
Your code appears to be unclean for the following reasons:

1. The `validateForm` function is called in both the save and connect functions, resulting in duplication within the `handleSave` and `connect` functions.
2. From my perspective, the only difference seems to be a `$emit('refresh')` in one case and a `$emit('connect')` in the other. Is that correct?

2024-03-26 09:36 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +  }
We need a function, `handleSave`, to handle all the save logic, determining through a parameter `type: connect | save` whether it's a connection or just a save. Then, in different action events, call this `handleSave`, handling different logic according to the type. This would make the code simpler, right?

2024-03-26 09:37 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +  }
Same in the Web version code.

2024-03-26 13:04 UTC, ni00 requested changes

2024-03-26 13:06 UTC, ni00 commented on src/lang/common.ts
> +    en: 'Save Success',
It seems that it can be changed or not.

2024-03-26 14:37 UTC, XL-YiBai commented on src/views/connections/ConnectionForm.vue
> +  }
Yes, the code here  seems to have some redundancies. After making the suggested modifications, the code indeed appears more concise. Thank you very much for the insightful suggestion! 🍻

2024-03-26 14:40 UTC, XL-YiBai commented on src/lang/common.ts
> +    en: 'Save Success',
Thank you for your suggestion.🍻  But I think the translation here should be consistent with other places, such as `Edit Success` and `Delete Success`.

2024-03-27 01:45 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +    } else {
Even with save, there's still a chance of failure after saving the data...

Do not add error messages for creation or editing failures; only include them in the connection section.

2024-03-27 01:49 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +    }
It's recommended to use `save` for commands, as `handleSave` sounds more like a function name.

Consider future scalability.

```suggestion
  private handleActionCommand(command: 'save') {
    if (command === 'save') {
      this.handleSave('save')
    }
```

2024-03-27 06:46 UTC, ysfscream approved these changes
LGTM! Thanks

2024-03-27 06:46 UTC, merged