docs(web-readme): add docker local deployment guide
emqx/MQTTX pull request #1621
Opened 2024-04-07 03:32 UTC by DM1-1

### PR Checklist

If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md)

#### What is the current behavior?

#### Issue Number

#1575 

#### What is the new behavior?

Add docker local deployment guide. 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

#### Specific Instructions

Support for PR#1619

#### Other information

2024-04-08 06:06 UTC, Red-Asuka commented on web/README-CN.md
> +支持通过 env 修改配置，编译后可以使用 Nginx 或者 Docker 部署 MQTTX Web。
如果你需要进行某些个性化设置，例如改变默认的连接路径、部署路径等，你可以编辑 `.env` 配置文件并手动编译来实现这些修改。如果你想知道如何编译项目和打包 docker 镜像，你可以参考我们的开发部分。

2024-04-08 06:06 UTC, Red-Asuka commented on web/README.md
> +Supports modifying configuration through env, and after compilation, you can deploy MQTTX Web using Nginx or Docker.
If you need to make some personalized settings, such as changing the default connection path, deployment path, etc., you can achieve these modifications by editing the `.env` configuration file and compiling manually. For information on how to compile the project and package docker images, you can refer to the development section.

2024-04-09 01:58 UTC, Red-Asuka requested changes

2024-04-09 01:58 UTC, Red-Asuka commented on web/README-CN.md
> +# 编译和压缩以构建生产版本，用于Docker容器化
Spaces are needed between Chinese and English texts.

2024-04-09 01:58 UTC, Red-Asuka commented on web/README-CN.md
> +# 运行 docker 镜像
docker -> Docker

2024-04-09 01:58 UTC, Red-Asuka commented on web/README.md
> +If you need to make some personalized settings, such as changing the default connection path, deployment path, etc., you can achieve these modifications by editing the .env configuration file and com
The anchor is incorrect.

2024-04-09 02:15 UTC, ysfscream commented
@DM1-1 It seems that I haven't seen updates on the instructions for configuration use, but that's fine. We need to update the documentation at https://github.com/emqx/mqttx-site. After the update, I will introduce how to customize configuration packaging in a new blog post about mqttx-web.

2024-04-09 02:56 UTC, DM1-1 commented
> @DM1-1 It seems that I haven't seen updates on the instructions for configuration use, but that's fine. We need to update the documentation at https://github.com/emqx/mqttx-site. After the update, I will introduce how to customize configuration packaging in a new blog post about mqttx-web.

I agree with your point that this content is indeed more suitable for presentation through an article.

2024-04-09 05:43 UTC, ysfscream commented
@DM1-1 YES. But you still need to clearly these configs in the web docs on mqttx.app, I will directly refer to it later. Thank you.

2024-04-09 06:07 UTC, ysfscream approved these changes

2024-04-09 06:12 UTC, DM1-1 commented
> @DM1-1 YES. But you still need to clearly these configs in the web docs on mqttx.app, I will directly refer to it later. Thank you.
OK. I will complete the web docs during my available time and ensure that it is promptly updated on mqttx.app.

2024-04-09 06:14 UTC, Red-Asuka approved these changes

2024-04-09 06:14 UTC, merged