feat(connection): support append timestamp to MQTT client id.
emqx/MQTTX pull request #401
Opened 2020-12-10 11:18 UTC by oceanlvr

[https://github.com/emqx/MQTTX/issues/394#event-4082449360](https://github.com/emqx/MQTTX/issues/394#event-4082449360)

2020-12-11 01:20 UTC, ysfscream commented
I think your PR commit did not pull the upstream branch dev/1.4.2 to the latest, beacuse the file `manual-cn.md` has been modified in the previous commit. Please check.

2020-12-11 01:49 UTC, ysfscream requested changes

2020-12-11 01:49 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +              </a>
Please add a `Tooltip` component in order to explain what this button does.

2020-12-11 01:49 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +  }
Append method should not be implemented here. Should be added when creating MQTT client options.

2020-12-11 03:35 UTC, ysfscream requested changes

2020-12-11 03:35 UTC, ysfscream commented on src/views/connections/ConnectionForm.vue
> +                v-if="oper === 'create'"
Remove `v-if`, because it can also be modified when editing.

2020-12-11 03:41 UTC, ysfscream commented
Could you please add this feature to the `ConnectionInfo` component? You can add this time icon next to the ClientID label as shown below.

2020-12-11 10:10 UTC, 0721Betty commented on src/utils/mqttUtils.ts
> +  if (clientIdWithTime === true) {
if(clientIdWithTime)?

2020-12-13 14:15 UTC, ysfscream commented on src/utils/mqttUtils.ts
> +  if (clientIdWithTime === true) {
Is a good suggestion.

2020-12-14 05:45 UTC, ysfscream approved these changes

2020-12-14 05:47 UTC, 0721Betty approved these changes

2020-12-14 05:47 UTC, merged